/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Business Partner Tax Number
 */
@ApiModel(description = "Business Partner Tax Number")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-01T06:30:25.755Z")
public class APIBUSINESSPARTNERABusinessPartnerTaxNumberType {
  @SerializedName("BusinessPartner")
  private String businessPartner = null;

  @SerializedName("BPTaxType")
  private String bpTaxType = null;

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.
   * @return businessPartner
  **/
  @ApiModelProperty(value = "Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.")
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABusinessPartnerTaxNumberType bpTaxType(String bpTaxType) {
    this.bpTaxType = bpTaxType;
    return this;
  }

   /**
   * Specifies the tax number category.
   * @return bpTaxType
  **/
  @ApiModelProperty(value = "Specifies the tax number category.")
  public String getBpTaxType() {
    return bpTaxType;
  }

  public void setBpTaxType(String bpTaxType) {
    this.bpTaxType = bpTaxType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerTaxNumberType apIBUSINESSPARTNERABusinessPartnerTaxNumberType = (APIBUSINESSPARTNERABusinessPartnerTaxNumberType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.businessPartner) &&
        Objects.equals(this.bpTaxType, apIBUSINESSPARTNERABusinessPartnerTaxNumberType.bpTaxType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, bpTaxType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerTaxNumberType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    bpTaxType: ").append(toIndentedString(bpTaxType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

