/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Address Email Address
 */
@ApiModel(description = "Address Email Address")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-01T06:30:25.755Z")
public class APIBUSINESSPARTNERAAddressEmailAddressType {
  @SerializedName("AddressID")
  private String addressID = null;

  @SerializedName("Person")
  private String person = null;

  @SerializedName("OrdinalNumber")
  private String ordinalNumber = null;

  public APIBUSINESSPARTNERAAddressEmailAddressType addressID(String addressID) {
    this.addressID = addressID;
    return this;
  }

   /**
   * Internal key for identifying a Business Address Services address.   For more information about the meaning and use of the address number and the Business Address Services concepts, see the function group SZA0 documentation.
   * @return addressID
  **/
  @ApiModelProperty(value = "Internal key for identifying a Business Address Services address.   For more information about the meaning and use of the address number and the Business Address Services concepts, see the function group SZA0 documentation.")
  public String getAddressID() {
    return addressID;
  }

  public void setAddressID(String addressID) {
    this.addressID = addressID;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressType person(String person) {
    this.person = person;
    return this;
  }

   /**
   * Internal key for identifying a person in Business Address Services.   For more information about the meaning and use of the person number and Business Address Services concepts, see the function group SZA0 documentation.
   * @return person
  **/
  @ApiModelProperty(value = "Internal key for identifying a person in Business Address Services.   For more information about the meaning and use of the person number and Business Address Services concepts, see the function group SZA0 documentation.")
  public String getPerson() {
    return person;
  }

  public void setPerson(String person) {
    this.person = person;
  }

  public APIBUSINESSPARTNERAAddressEmailAddressType ordinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
    return this;
  }

   /**
   * Sequence Number
   * @return ordinalNumber
  **/
  @ApiModelProperty(value = "Sequence Number")
  public String getOrdinalNumber() {
    return ordinalNumber;
  }

  public void setOrdinalNumber(String ordinalNumber) {
    this.ordinalNumber = ordinalNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERAAddressEmailAddressType apIBUSINESSPARTNERAAddressEmailAddressType = (APIBUSINESSPARTNERAAddressEmailAddressType) o;
    return Objects.equals(this.addressID, apIBUSINESSPARTNERAAddressEmailAddressType.addressID) &&
        Objects.equals(this.person, apIBUSINESSPARTNERAAddressEmailAddressType.person) &&
        Objects.equals(this.ordinalNumber, apIBUSINESSPARTNERAAddressEmailAddressType.ordinalNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressID, person, ordinalNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERAAddressEmailAddressType {\n");
    
    sb.append("    addressID: ").append(toIndentedString(addressID)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    ordinalNumber: ").append(toIndentedString(ordinalNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

