/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERABPContactToFuncAndDeptType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABPContactToAddressType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Business Partner Contact
 */
@ApiModel(description = "Business Partner Contact")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-01T06:30:25.755Z")
public class APIBUSINESSPARTNERABusinessPartnerContactType {
  @SerializedName("RelationshipNumber")
  private String relationshipNumber = null;

  @SerializedName("BusinessPartnerCompany")
  private String businessPartnerCompany = null;

  @SerializedName("BusinessPartnerPerson")
  private String businessPartnerPerson = null;

  @SerializedName("ValidityEndDate")
  private String validityEndDate = null;

  @SerializedName("to_ContactAddress")
  private CollectionOfABPContactToAddressType toContactAddress = null;

  @SerializedName("to_ContactRelationship")
  private APIBUSINESSPARTNERABPContactToFuncAndDeptType toContactRelationship = null;

  public APIBUSINESSPARTNERABusinessPartnerContactType relationshipNumber(String relationshipNumber) {
    this.relationshipNumber = relationshipNumber;
    return this;
  }

   /**
   * BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set.
   * @return relationshipNumber
  **/
  @ApiModelProperty(value = "BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set.")
  public String getRelationshipNumber() {
    return relationshipNumber;
  }

  public void setRelationshipNumber(String relationshipNumber) {
    this.relationshipNumber = relationshipNumber;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactType businessPartnerCompany(String businessPartnerCompany) {
    this.businessPartnerCompany = businessPartnerCompany;
    return this;
  }

   /**
   * Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.
   * @return businessPartnerCompany
  **/
  @ApiModelProperty(value = "Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.")
  public String getBusinessPartnerCompany() {
    return businessPartnerCompany;
  }

  public void setBusinessPartnerCompany(String businessPartnerCompany) {
    this.businessPartnerCompany = businessPartnerCompany;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactType businessPartnerPerson(String businessPartnerPerson) {
    this.businessPartnerPerson = businessPartnerPerson;
    return this;
  }

   /**
   * Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.
   * @return businessPartnerPerson
  **/
  @ApiModelProperty(value = "Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.")
  public String getBusinessPartnerPerson() {
    return businessPartnerPerson;
  }

  public void setBusinessPartnerPerson(String businessPartnerPerson) {
    this.businessPartnerPerson = businessPartnerPerson;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactType validityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
    return this;
  }

   /**
   * Validity Date (Valid To)
   * @return validityEndDate
  **/
  @ApiModelProperty(example = "/Date(1492041600000)/", value = "Validity Date (Valid To)")
  public String getValidityEndDate() {
    return validityEndDate;
  }

  public void setValidityEndDate(String validityEndDate) {
    this.validityEndDate = validityEndDate;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactType toContactAddress(CollectionOfABPContactToAddressType toContactAddress) {
    this.toContactAddress = toContactAddress;
    return this;
  }

   /**
   * Get toContactAddress
   * @return toContactAddress
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABPContactToAddressType getToContactAddress() {
    return toContactAddress;
  }

  public void setToContactAddress(CollectionOfABPContactToAddressType toContactAddress) {
    this.toContactAddress = toContactAddress;
  }

  public APIBUSINESSPARTNERABusinessPartnerContactType toContactRelationship(APIBUSINESSPARTNERABPContactToFuncAndDeptType toContactRelationship) {
    this.toContactRelationship = toContactRelationship;
    return this;
  }

   /**
   * Get toContactRelationship
   * @return toContactRelationship
  **/
  @ApiModelProperty(value = "")
  public APIBUSINESSPARTNERABPContactToFuncAndDeptType getToContactRelationship() {
    return toContactRelationship;
  }

  public void setToContactRelationship(APIBUSINESSPARTNERABPContactToFuncAndDeptType toContactRelationship) {
    this.toContactRelationship = toContactRelationship;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerContactType apIBUSINESSPARTNERABusinessPartnerContactType = (APIBUSINESSPARTNERABusinessPartnerContactType) o;
    return Objects.equals(this.relationshipNumber, apIBUSINESSPARTNERABusinessPartnerContactType.relationshipNumber) &&
        Objects.equals(this.businessPartnerCompany, apIBUSINESSPARTNERABusinessPartnerContactType.businessPartnerCompany) &&
        Objects.equals(this.businessPartnerPerson, apIBUSINESSPARTNERABusinessPartnerContactType.businessPartnerPerson) &&
        Objects.equals(this.validityEndDate, apIBUSINESSPARTNERABusinessPartnerContactType.validityEndDate) &&
        Objects.equals(this.toContactAddress, apIBUSINESSPARTNERABusinessPartnerContactType.toContactAddress) &&
        Objects.equals(this.toContactRelationship, apIBUSINESSPARTNERABusinessPartnerContactType.toContactRelationship);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, toContactAddress, toContactRelationship);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerContactType {\n");
    
    sb.append("    relationshipNumber: ").append(toIndentedString(relationshipNumber)).append("\n");
    sb.append("    businessPartnerCompany: ").append(toIndentedString(businessPartnerCompany)).append("\n");
    sb.append("    businessPartnerPerson: ").append(toIndentedString(businessPartnerPerson)).append("\n");
    sb.append("    validityEndDate: ").append(toIndentedString(validityEndDate)).append("\n");
    sb.append("    toContactAddress: ").append(toIndentedString(toContactAddress)).append("\n");
    sb.append("    toContactRelationship: ").append(toIndentedString(toContactRelationship)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

