/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERACustomerType;
import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERASupplierType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABuPaIdentificationType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABusinessPartnerAddressType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABusinessPartnerBankType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABusinessPartnerContactType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABusinessPartnerRoleType;
import com.sap.apibhub.sdk.api_business_partner.model.CollectionOfABusinessPartnerTaxNumberType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Business Partner
 */
@ApiModel(description = "Business Partner")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-01T06:30:25.755Z")
public class APIBUSINESSPARTNERABusinessPartnerType {
  @SerializedName("BusinessPartner")
  private String businessPartner = null;

  @SerializedName("to_BuPaIdentification")
  private CollectionOfABuPaIdentificationType toBuPaIdentification = null;

  @SerializedName("to_BusinessPartnerAddress")
  private CollectionOfABusinessPartnerAddressType toBusinessPartnerAddress = null;

  @SerializedName("to_BusinessPartnerBank")
  private CollectionOfABusinessPartnerBankType toBusinessPartnerBank = null;

  @SerializedName("to_BusinessPartnerContact")
  private CollectionOfABusinessPartnerContactType toBusinessPartnerContact = null;

  @SerializedName("to_BusinessPartnerRole")
  private CollectionOfABusinessPartnerRoleType toBusinessPartnerRole = null;

  @SerializedName("to_BusinessPartnerTax")
  private CollectionOfABusinessPartnerTaxNumberType toBusinessPartnerTax = null;

  @SerializedName("to_Customer")
  private APIBUSINESSPARTNERACustomerType toCustomer = null;

  @SerializedName("to_Supplier")
  private APIBUSINESSPARTNERASupplierType toSupplier = null;

  public APIBUSINESSPARTNERABusinessPartnerType businessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
    return this;
  }

   /**
   * Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.
   * @return businessPartner
  **/
  @ApiModelProperty(value = "Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client.")
  public String getBusinessPartner() {
    return businessPartner;
  }

  public void setBusinessPartner(String businessPartner) {
    this.businessPartner = businessPartner;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBuPaIdentification(CollectionOfABuPaIdentificationType toBuPaIdentification) {
    this.toBuPaIdentification = toBuPaIdentification;
    return this;
  }

   /**
   * Get toBuPaIdentification
   * @return toBuPaIdentification
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABuPaIdentificationType getToBuPaIdentification() {
    return toBuPaIdentification;
  }

  public void setToBuPaIdentification(CollectionOfABuPaIdentificationType toBuPaIdentification) {
    this.toBuPaIdentification = toBuPaIdentification;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBusinessPartnerAddress(CollectionOfABusinessPartnerAddressType toBusinessPartnerAddress) {
    this.toBusinessPartnerAddress = toBusinessPartnerAddress;
    return this;
  }

   /**
   * Get toBusinessPartnerAddress
   * @return toBusinessPartnerAddress
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABusinessPartnerAddressType getToBusinessPartnerAddress() {
    return toBusinessPartnerAddress;
  }

  public void setToBusinessPartnerAddress(CollectionOfABusinessPartnerAddressType toBusinessPartnerAddress) {
    this.toBusinessPartnerAddress = toBusinessPartnerAddress;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBusinessPartnerBank(CollectionOfABusinessPartnerBankType toBusinessPartnerBank) {
    this.toBusinessPartnerBank = toBusinessPartnerBank;
    return this;
  }

   /**
   * Get toBusinessPartnerBank
   * @return toBusinessPartnerBank
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABusinessPartnerBankType getToBusinessPartnerBank() {
    return toBusinessPartnerBank;
  }

  public void setToBusinessPartnerBank(CollectionOfABusinessPartnerBankType toBusinessPartnerBank) {
    this.toBusinessPartnerBank = toBusinessPartnerBank;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBusinessPartnerContact(CollectionOfABusinessPartnerContactType toBusinessPartnerContact) {
    this.toBusinessPartnerContact = toBusinessPartnerContact;
    return this;
  }

   /**
   * Get toBusinessPartnerContact
   * @return toBusinessPartnerContact
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABusinessPartnerContactType getToBusinessPartnerContact() {
    return toBusinessPartnerContact;
  }

  public void setToBusinessPartnerContact(CollectionOfABusinessPartnerContactType toBusinessPartnerContact) {
    this.toBusinessPartnerContact = toBusinessPartnerContact;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBusinessPartnerRole(CollectionOfABusinessPartnerRoleType toBusinessPartnerRole) {
    this.toBusinessPartnerRole = toBusinessPartnerRole;
    return this;
  }

   /**
   * Get toBusinessPartnerRole
   * @return toBusinessPartnerRole
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABusinessPartnerRoleType getToBusinessPartnerRole() {
    return toBusinessPartnerRole;
  }

  public void setToBusinessPartnerRole(CollectionOfABusinessPartnerRoleType toBusinessPartnerRole) {
    this.toBusinessPartnerRole = toBusinessPartnerRole;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toBusinessPartnerTax(CollectionOfABusinessPartnerTaxNumberType toBusinessPartnerTax) {
    this.toBusinessPartnerTax = toBusinessPartnerTax;
    return this;
  }

   /**
   * Get toBusinessPartnerTax
   * @return toBusinessPartnerTax
  **/
  @ApiModelProperty(value = "")
  public CollectionOfABusinessPartnerTaxNumberType getToBusinessPartnerTax() {
    return toBusinessPartnerTax;
  }

  public void setToBusinessPartnerTax(CollectionOfABusinessPartnerTaxNumberType toBusinessPartnerTax) {
    this.toBusinessPartnerTax = toBusinessPartnerTax;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toCustomer(APIBUSINESSPARTNERACustomerType toCustomer) {
    this.toCustomer = toCustomer;
    return this;
  }

   /**
   * Get toCustomer
   * @return toCustomer
  **/
  @ApiModelProperty(value = "")
  public APIBUSINESSPARTNERACustomerType getToCustomer() {
    return toCustomer;
  }

  public void setToCustomer(APIBUSINESSPARTNERACustomerType toCustomer) {
    this.toCustomer = toCustomer;
  }

  public APIBUSINESSPARTNERABusinessPartnerType toSupplier(APIBUSINESSPARTNERASupplierType toSupplier) {
    this.toSupplier = toSupplier;
    return this;
  }

   /**
   * Get toSupplier
   * @return toSupplier
  **/
  @ApiModelProperty(value = "")
  public APIBUSINESSPARTNERASupplierType getToSupplier() {
    return toSupplier;
  }

  public void setToSupplier(APIBUSINESSPARTNERASupplierType toSupplier) {
    this.toSupplier = toSupplier;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APIBUSINESSPARTNERABusinessPartnerType apIBUSINESSPARTNERABusinessPartnerType = (APIBUSINESSPARTNERABusinessPartnerType) o;
    return Objects.equals(this.businessPartner, apIBUSINESSPARTNERABusinessPartnerType.businessPartner) &&
        Objects.equals(this.toBuPaIdentification, apIBUSINESSPARTNERABusinessPartnerType.toBuPaIdentification) &&
        Objects.equals(this.toBusinessPartnerAddress, apIBUSINESSPARTNERABusinessPartnerType.toBusinessPartnerAddress) &&
        Objects.equals(this.toBusinessPartnerBank, apIBUSINESSPARTNERABusinessPartnerType.toBusinessPartnerBank) &&
        Objects.equals(this.toBusinessPartnerContact, apIBUSINESSPARTNERABusinessPartnerType.toBusinessPartnerContact) &&
        Objects.equals(this.toBusinessPartnerRole, apIBUSINESSPARTNERABusinessPartnerType.toBusinessPartnerRole) &&
        Objects.equals(this.toBusinessPartnerTax, apIBUSINESSPARTNERABusinessPartnerType.toBusinessPartnerTax) &&
        Objects.equals(this.toCustomer, apIBUSINESSPARTNERABusinessPartnerType.toCustomer) &&
        Objects.equals(this.toSupplier, apIBUSINESSPARTNERABusinessPartnerType.toSupplier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessPartner, toBuPaIdentification, toBusinessPartnerAddress, toBusinessPartnerBank, toBusinessPartnerContact, toBusinessPartnerRole, toBusinessPartnerTax, toCustomer, toSupplier);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIBUSINESSPARTNERABusinessPartnerType {\n");
    
    sb.append("    businessPartner: ").append(toIndentedString(businessPartner)).append("\n");
    sb.append("    toBuPaIdentification: ").append(toIndentedString(toBuPaIdentification)).append("\n");
    sb.append("    toBusinessPartnerAddress: ").append(toIndentedString(toBusinessPartnerAddress)).append("\n");
    sb.append("    toBusinessPartnerBank: ").append(toIndentedString(toBusinessPartnerBank)).append("\n");
    sb.append("    toBusinessPartnerContact: ").append(toIndentedString(toBusinessPartnerContact)).append("\n");
    sb.append("    toBusinessPartnerRole: ").append(toIndentedString(toBusinessPartnerRole)).append("\n");
    sb.append("    toBusinessPartnerTax: ").append(toIndentedString(toBusinessPartnerTax)).append("\n");
    sb.append("    toCustomer: ").append(toIndentedString(toCustomer)).append("\n");
    sb.append("    toSupplier: ").append(toIndentedString(toSupplier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

