/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk.api_business_partner.model.ABPContactToFuncAndDeptType;
import com.sap.apibhub.sdk.api_business_partner.model.ModifiedABPContactToFuncAndDeptType;
import com.sap.apibhub.sdk.api_business_partner.model.OdataError;
import com.sap.apibhub.sdk.api_business_partner.model.Wrapper5;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ABPContactToFuncAndDeptApi {
    private ApiClient apiClient;

    public ABPContactToFuncAndDeptApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ABPContactToFuncAndDeptApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for aBPContactToFuncAndDeptGet */
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptGetCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BPContactToFuncAndDept".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (top != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$top", top));
        if (skip != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$skip", skip));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$filter", filter));
        if (inlinecount != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$inlinecount", inlinecount));
        if (orderby != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$orderby", orderby));
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptGetValidateBeforeCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptGetCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entities from A_BPContactToFuncAndDept
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return Wrapper5
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Wrapper5 aBPContactToFuncAndDeptGet(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        ApiResponse<Wrapper5> resp = aBPContactToFuncAndDeptGetWithHttpInfo(top, skip, filter, inlinecount, orderby, select);
        return resp.getData();
    }

    /**
     * Get entities from A_BPContactToFuncAndDept
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;Wrapper5&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Wrapper5> aBPContactToFuncAndDeptGetWithHttpInfo(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, null, null);
        Type localVarReturnType = new TypeToken<Wrapper5>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entities from A_BPContactToFuncAndDept (asynchronously)
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBPContactToFuncAndDeptGetAsync(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ApiCallback<Wrapper5> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Wrapper5>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet */
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetCall(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BPContactToFuncAndDept(RelationshipNumber='{RelationshipNumber}',BusinessPartnerCompany='{BusinessPartnerCompany}',BusinessPartnerPerson='{BusinessPartnerPerson}',ValidityEndDate={ValidityEndDate})".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "RelationshipNumber" + "\\}", apiClient.escapeString(relationshipNumber.toString()))
        .replaceAll("\\{" + "BusinessPartnerCompany" + "\\}", apiClient.escapeString(businessPartnerCompany.toString()))
        .replaceAll("\\{" + "BusinessPartnerPerson" + "\\}", apiClient.escapeString(businessPartnerPerson.toString()))
        .replaceAll("\\{" + "ValidityEndDate" + "\\}", apiClient.escapeString(validityEndDate.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetValidateBeforeCall(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'relationshipNumber' is set
        if (relationshipNumber == null) {
            throw new ApiException("Missing the required parameter 'relationshipNumber' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet(Async)");
        }
        
        // verify the required parameter 'businessPartnerCompany' is set
        if (businessPartnerCompany == null) {
            throw new ApiException("Missing the required parameter 'businessPartnerCompany' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet(Async)");
        }
        
        // verify the required parameter 'businessPartnerPerson' is set
        if (businessPartnerPerson == null) {
            throw new ApiException("Missing the required parameter 'businessPartnerPerson' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet(Async)");
        }
        
        // verify the required parameter 'validityEndDate' is set
        if (validityEndDate == null) {
            throw new ApiException("Missing the required parameter 'validityEndDate' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entity from A_BPContactToFuncAndDept by key
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ABPContactToFuncAndDeptType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ABPContactToFuncAndDeptType aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGet(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, List<String> select) throws ApiException {
        ApiResponse<ABPContactToFuncAndDeptType> resp = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetWithHttpInfo(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, select);
        return resp.getData();
    }

    /**
     * Get entity from A_BPContactToFuncAndDept by key
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;ABPContactToFuncAndDeptType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ABPContactToFuncAndDeptType> aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetWithHttpInfo(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetValidateBeforeCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, select, null, null);
        Type localVarReturnType = new TypeToken<ABPContactToFuncAndDeptType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entity from A_BPContactToFuncAndDept by key (asynchronously)
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetAsync(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, List<String> select, final ApiCallback<ABPContactToFuncAndDeptType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDateGetValidateBeforeCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ABPContactToFuncAndDeptType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch */
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchCall(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, ModifiedABPContactToFuncAndDeptType aBPContactToFuncAndDeptType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aBPContactToFuncAndDeptType;
        
        // create path and map variables
        String localVarPath = "/A_BPContactToFuncAndDept(RelationshipNumber='{RelationshipNumber}',BusinessPartnerCompany='{BusinessPartnerCompany}',BusinessPartnerPerson='{BusinessPartnerPerson}',ValidityEndDate={ValidityEndDate})".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "RelationshipNumber" + "\\}", apiClient.escapeString(relationshipNumber.toString()))
        .replaceAll("\\{" + "BusinessPartnerCompany" + "\\}", apiClient.escapeString(businessPartnerCompany.toString()))
        .replaceAll("\\{" + "BusinessPartnerPerson" + "\\}", apiClient.escapeString(businessPartnerPerson.toString()))
        .replaceAll("\\{" + "ValidityEndDate" + "\\}", apiClient.escapeString(validityEndDate.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchValidateBeforeCall(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, ModifiedABPContactToFuncAndDeptType aBPContactToFuncAndDeptType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'relationshipNumber' is set
        if (relationshipNumber == null) {
            throw new ApiException("Missing the required parameter 'relationshipNumber' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch(Async)");
        }
        
        // verify the required parameter 'businessPartnerCompany' is set
        if (businessPartnerCompany == null) {
            throw new ApiException("Missing the required parameter 'businessPartnerCompany' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch(Async)");
        }
        
        // verify the required parameter 'businessPartnerPerson' is set
        if (businessPartnerPerson == null) {
            throw new ApiException("Missing the required parameter 'businessPartnerPerson' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch(Async)");
        }
        
        // verify the required parameter 'validityEndDate' is set
        if (validityEndDate == null) {
            throw new ApiException("Missing the required parameter 'validityEndDate' when calling aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, aBPContactToFuncAndDeptType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in A_BPContactToFuncAndDept
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param aBPContactToFuncAndDeptType New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatch(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, ModifiedABPContactToFuncAndDeptType aBPContactToFuncAndDeptType) throws ApiException {
        aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchWithHttpInfo(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, aBPContactToFuncAndDeptType);
    }

    /**
     * Update entity in A_BPContactToFuncAndDept
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param aBPContactToFuncAndDeptType New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchWithHttpInfo(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, ModifiedABPContactToFuncAndDeptType aBPContactToFuncAndDeptType) throws ApiException {
        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchValidateBeforeCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, aBPContactToFuncAndDeptType, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in A_BPContactToFuncAndDept (asynchronously)
     * 
     * @param relationshipNumber BP Relationship Number   The business partner relationship number is an internal number that identifies the business partner relationship set. (required)
     * @param businessPartnerCompany Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param businessPartnerPerson Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param validityEndDate Validity Date (Valid To) (required)
     * @param aBPContactToFuncAndDeptType New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchAsync(String relationshipNumber, String businessPartnerCompany, String businessPartnerPerson, String validityEndDate, ModifiedABPContactToFuncAndDeptType aBPContactToFuncAndDeptType, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBPContactToFuncAndDeptRelationshipNumberRelationshipNumberBusinessPartnerCompanyBusinessPartnerCompanyBusinessPartnerPersonBusinessPartnerPersonValidityEndDateValidityEndDatePatchValidateBeforeCall(relationshipNumber, businessPartnerCompany, businessPartnerPerson, validityEndDate, aBPContactToFuncAndDeptType, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
