/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERABusinessPartnerBankType;
import com.sap.apibhub.sdk.api_business_partner.model.CreatedABusinessPartnerBankType;
import com.sap.apibhub.sdk.api_business_partner.model.ModifiedABusinessPartnerBankType;
import com.sap.apibhub.sdk.api_business_partner.model.OdataError;
import com.sap.apibhub.sdk.api_business_partner.model.Wrapper10;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ABusinessPartnerBankApi {
    private ApiClient apiClient;

    public ABusinessPartnerBankApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ABusinessPartnerBankApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete */
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteCall(String businessPartner, String bankIdentification, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerBank(BusinessPartner='{BusinessPartner}',BankIdentification='{BankIdentification}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BankIdentification" + "\\}", apiClient.escapeString(bankIdentification.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (ifMatch != null)
        localVarHeaderParams.put("If-Match", apiClient.parameterToString(ifMatch));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteValidateBeforeCall(String businessPartner, String bankIdentification, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete(Async)");
        }
        
        // verify the required parameter 'bankIdentification' is set
        if (bankIdentification == null) {
            throw new ApiException("Missing the required parameter 'bankIdentification' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteCall(businessPartner, bankIdentification, ifMatch, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete entity from A_BusinessPartnerBank
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param ifMatch ETag (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDelete(String businessPartner, String bankIdentification, String ifMatch) throws ApiException {
        aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteWithHttpInfo(businessPartner, bankIdentification, ifMatch);
    }

    /**
     * Delete entity from A_BusinessPartnerBank
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param ifMatch ETag (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteWithHttpInfo(String businessPartner, String bankIdentification, String ifMatch) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteValidateBeforeCall(businessPartner, bankIdentification, ifMatch, null, null);
        return apiClient.execute(call);
    }

    /**
     * Delete entity from A_BusinessPartnerBank (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param ifMatch ETag (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteAsync(String businessPartner, String bankIdentification, String ifMatch, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationDeleteValidateBeforeCall(businessPartner, bankIdentification, ifMatch, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet */
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetCall(String businessPartner, String bankIdentification, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerBank(BusinessPartner='{BusinessPartner}',BankIdentification='{BankIdentification}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BankIdentification" + "\\}", apiClient.escapeString(bankIdentification.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetValidateBeforeCall(String businessPartner, String bankIdentification, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet(Async)");
        }
        
        // verify the required parameter 'bankIdentification' is set
        if (bankIdentification == null) {
            throw new ApiException("Missing the required parameter 'bankIdentification' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetCall(businessPartner, bankIdentification, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entity from A_BusinessPartnerBank by key
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return CreatedABusinessPartnerBankType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedABusinessPartnerBankType aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGet(String businessPartner, String bankIdentification, List<String> select) throws ApiException {
        ApiResponse<CreatedABusinessPartnerBankType> resp = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetWithHttpInfo(businessPartner, bankIdentification, select);
        return resp.getData();
    }

    /**
     * Get entity from A_BusinessPartnerBank by key
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;CreatedABusinessPartnerBankType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedABusinessPartnerBankType> aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetWithHttpInfo(String businessPartner, String bankIdentification, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetValidateBeforeCall(businessPartner, bankIdentification, select, null, null);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerBankType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entity from A_BusinessPartnerBank by key (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetAsync(String businessPartner, String bankIdentification, List<String> select, final ApiCallback<CreatedABusinessPartnerBankType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationGetValidateBeforeCall(businessPartner, bankIdentification, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerBankType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch */
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchCall(String businessPartner, String bankIdentification, ModifiedABusinessPartnerBankType aBusinessPartnerBankType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aBusinessPartnerBankType;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerBank(BusinessPartner='{BusinessPartner}',BankIdentification='{BankIdentification}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BankIdentification" + "\\}", apiClient.escapeString(bankIdentification.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchValidateBeforeCall(String businessPartner, String bankIdentification, ModifiedABusinessPartnerBankType aBusinessPartnerBankType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch(Async)");
        }
        
        // verify the required parameter 'bankIdentification' is set
        if (bankIdentification == null) {
            throw new ApiException("Missing the required parameter 'bankIdentification' when calling aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchCall(businessPartner, bankIdentification, aBusinessPartnerBankType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in A_BusinessPartnerBank
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param aBusinessPartnerBankType New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatch(String businessPartner, String bankIdentification, ModifiedABusinessPartnerBankType aBusinessPartnerBankType) throws ApiException {
        aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchWithHttpInfo(businessPartner, bankIdentification, aBusinessPartnerBankType);
    }

    /**
     * Update entity in A_BusinessPartnerBank
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param aBusinessPartnerBankType New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchWithHttpInfo(String businessPartner, String bankIdentification, ModifiedABusinessPartnerBankType aBusinessPartnerBankType) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchValidateBeforeCall(businessPartner, bankIdentification, aBusinessPartnerBankType, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in A_BusinessPartnerBank (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bankIdentification Key identifying a business partner&#39;s bank details.   Enter a bank details ID for each separate set of bank details for a business partner.Business Partner: H. MillerBD-ID Fin.institution   Acct no. 0001 Chemical Bank, NYC 56234560002 Chemical Bank, NYC 56231220003 First Bank of Pittsburgh ...Business partner: T.Wolsey and Co.BD-ID Fin.institution   Acct no.GIR0 Citibank, Charleston ...GIR1 Chemical Bank, NYC ... (required)
     * @param aBusinessPartnerBankType New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchAsync(String businessPartner, String bankIdentification, ModifiedABusinessPartnerBankType aBusinessPartnerBankType, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerBankBusinessPartnerBusinessPartnerBankIdentificationBankIdentificationPatchValidateBeforeCall(businessPartner, bankIdentification, aBusinessPartnerBankType, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for aBusinessPartnerBankGet */
    private com.squareup.okhttp.Call aBusinessPartnerBankGetCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerBank".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (top != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$top", top));
        if (skip != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$skip", skip));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$filter", filter));
        if (inlinecount != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$inlinecount", inlinecount));
        if (orderby != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$orderby", orderby));
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerBankGetValidateBeforeCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerBankGetCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entities from A_BusinessPartnerBank
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return Wrapper10
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Wrapper10 aBusinessPartnerBankGet(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        ApiResponse<Wrapper10> resp = aBusinessPartnerBankGetWithHttpInfo(top, skip, filter, inlinecount, orderby, select);
        return resp.getData();
    }

    /**
     * Get entities from A_BusinessPartnerBank
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;Wrapper10&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Wrapper10> aBusinessPartnerBankGetWithHttpInfo(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerBankGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, null, null);
        Type localVarReturnType = new TypeToken<Wrapper10>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entities from A_BusinessPartnerBank (asynchronously)
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerBankGetAsync(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ApiCallback<Wrapper10> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerBankGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Wrapper10>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBusinessPartnerBankPost */
    private com.squareup.okhttp.Call aBusinessPartnerBankPostCall(APIBUSINESSPARTNERABusinessPartnerBankType aBusinessPartnerBankType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aBusinessPartnerBankType;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerBank".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerBankPostValidateBeforeCall(APIBUSINESSPARTNERABusinessPartnerBankType aBusinessPartnerBankType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerBankPostCall(aBusinessPartnerBankType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add new entity to A_BusinessPartnerBank
     * 
     * @param aBusinessPartnerBankType New entity (optional)
     * @return CreatedABusinessPartnerBankType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedABusinessPartnerBankType aBusinessPartnerBankPost(APIBUSINESSPARTNERABusinessPartnerBankType aBusinessPartnerBankType) throws ApiException {
        ApiResponse<CreatedABusinessPartnerBankType> resp = aBusinessPartnerBankPostWithHttpInfo(aBusinessPartnerBankType);
        return resp.getData();
    }

    /**
     * Add new entity to A_BusinessPartnerBank
     * 
     * @param aBusinessPartnerBankType New entity (optional)
     * @return ApiResponse&lt;CreatedABusinessPartnerBankType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedABusinessPartnerBankType> aBusinessPartnerBankPostWithHttpInfo(APIBUSINESSPARTNERABusinessPartnerBankType aBusinessPartnerBankType) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerBankPostValidateBeforeCall(aBusinessPartnerBankType, null, null);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerBankType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add new entity to A_BusinessPartnerBank (asynchronously)
     * 
     * @param aBusinessPartnerBankType New entity (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerBankPostAsync(APIBUSINESSPARTNERABusinessPartnerBankType aBusinessPartnerBankType, final ApiCallback<CreatedABusinessPartnerBankType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerBankPostValidateBeforeCall(aBusinessPartnerBankType, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerBankType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
