/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERABusinessPartnerTaxNumberType;
import com.sap.apibhub.sdk.api_business_partner.model.CreatedABusinessPartnerTaxNumberType;
import com.sap.apibhub.sdk.api_business_partner.model.ModifiedABusinessPartnerTaxNumberType;
import com.sap.apibhub.sdk.api_business_partner.model.OdataError;
import com.sap.apibhub.sdk.api_business_partner.model.Wrapper13;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ABusinessPartnerTaxNumberApi {
    private ApiClient apiClient;

    public ABusinessPartnerTaxNumberApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ABusinessPartnerTaxNumberApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDelete */
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteCall(String businessPartner, String bpTaxType, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerTaxNumber(BusinessPartner='{BusinessPartner}',BPTaxType='{BPTaxType}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BPTaxType" + "\\}", apiClient.escapeString(bpTaxType.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (ifMatch != null)
        localVarHeaderParams.put("If-Match", apiClient.parameterToString(ifMatch));

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteValidateBeforeCall(String businessPartner, String bpTaxType, String ifMatch, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDelete(Async)");
        }
        
        // verify the required parameter 'bpTaxType' is set
        if (bpTaxType == null) {
            throw new ApiException("Missing the required parameter 'bpTaxType' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDelete(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteCall(businessPartner, bpTaxType, ifMatch, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete entity from A_BusinessPartnerTaxNumber
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param ifMatch ETag (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDelete(String businessPartner, String bpTaxType, String ifMatch) throws ApiException {
        aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteWithHttpInfo(businessPartner, bpTaxType, ifMatch);
    }

    /**
     * Delete entity from A_BusinessPartnerTaxNumber
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param ifMatch ETag (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteWithHttpInfo(String businessPartner, String bpTaxType, String ifMatch) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteValidateBeforeCall(businessPartner, bpTaxType, ifMatch, null, null);
        return apiClient.execute(call);
    }

    /**
     * Delete entity from A_BusinessPartnerTaxNumber (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param ifMatch ETag (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteAsync(String businessPartner, String bpTaxType, String ifMatch, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeDeleteValidateBeforeCall(businessPartner, bpTaxType, ifMatch, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGet */
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetCall(String businessPartner, String bpTaxType, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerTaxNumber(BusinessPartner='{BusinessPartner}',BPTaxType='{BPTaxType}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BPTaxType" + "\\}", apiClient.escapeString(bpTaxType.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetValidateBeforeCall(String businessPartner, String bpTaxType, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGet(Async)");
        }
        
        // verify the required parameter 'bpTaxType' is set
        if (bpTaxType == null) {
            throw new ApiException("Missing the required parameter 'bpTaxType' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetCall(businessPartner, bpTaxType, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entity from A_BusinessPartnerTaxNumber by key
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return CreatedABusinessPartnerTaxNumberType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGet(String businessPartner, String bpTaxType, List<String> select) throws ApiException {
        ApiResponse<CreatedABusinessPartnerTaxNumberType> resp = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetWithHttpInfo(businessPartner, bpTaxType, select);
        return resp.getData();
    }

    /**
     * Get entity from A_BusinessPartnerTaxNumber by key
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;CreatedABusinessPartnerTaxNumberType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedABusinessPartnerTaxNumberType> aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetWithHttpInfo(String businessPartner, String bpTaxType, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetValidateBeforeCall(businessPartner, bpTaxType, select, null, null);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerTaxNumberType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entity from A_BusinessPartnerTaxNumber by key (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetAsync(String businessPartner, String bpTaxType, List<String> select, final ApiCallback<CreatedABusinessPartnerTaxNumberType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypeGetValidateBeforeCall(businessPartner, bpTaxType, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerTaxNumberType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatch */
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchCall(String businessPartner, String bpTaxType, ModifiedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aBusinessPartnerTaxNumberType;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerTaxNumber(BusinessPartner='{BusinessPartner}',BPTaxType='{BPTaxType}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "BusinessPartner" + "\\}", apiClient.escapeString(businessPartner.toString()))
        .replaceAll("\\{" + "BPTaxType" + "\\}", apiClient.escapeString(bpTaxType.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchValidateBeforeCall(String businessPartner, String bpTaxType, ModifiedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'businessPartner' is set
        if (businessPartner == null) {
            throw new ApiException("Missing the required parameter 'businessPartner' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatch(Async)");
        }
        
        // verify the required parameter 'bpTaxType' is set
        if (bpTaxType == null) {
            throw new ApiException("Missing the required parameter 'bpTaxType' when calling aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchCall(businessPartner, bpTaxType, aBusinessPartnerTaxNumberType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in A_BusinessPartnerTaxNumber
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param aBusinessPartnerTaxNumberType New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatch(String businessPartner, String bpTaxType, ModifiedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType) throws ApiException {
        aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchWithHttpInfo(businessPartner, bpTaxType, aBusinessPartnerTaxNumberType);
    }

    /**
     * Update entity in A_BusinessPartnerTaxNumber
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param aBusinessPartnerTaxNumberType New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchWithHttpInfo(String businessPartner, String bpTaxType, ModifiedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchValidateBeforeCall(businessPartner, bpTaxType, aBusinessPartnerTaxNumberType, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in A_BusinessPartnerTaxNumber (asynchronously)
     * 
     * @param businessPartner Business Partner Number   Key identifying a business partner in the SAP system. The key is unique within a client. (required)
     * @param bpTaxType Specifies the tax number category. (required)
     * @param aBusinessPartnerTaxNumberType New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchAsync(String businessPartner, String bpTaxType, ModifiedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberBusinessPartnerBusinessPartnerBPTaxTypeBPTaxTypePatchValidateBeforeCall(businessPartner, bpTaxType, aBusinessPartnerTaxNumberType, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for aBusinessPartnerTaxNumberGet */
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberGetCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerTaxNumber".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (top != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$top", top));
        if (skip != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$skip", skip));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$filter", filter));
        if (inlinecount != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$inlinecount", inlinecount));
        if (orderby != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$orderby", orderby));
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberGetValidateBeforeCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberGetCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entities from A_BusinessPartnerTaxNumber
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return Wrapper13
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Wrapper13 aBusinessPartnerTaxNumberGet(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        ApiResponse<Wrapper13> resp = aBusinessPartnerTaxNumberGetWithHttpInfo(top, skip, filter, inlinecount, orderby, select);
        return resp.getData();
    }

    /**
     * Get entities from A_BusinessPartnerTaxNumber
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @return ApiResponse&lt;Wrapper13&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Wrapper13> aBusinessPartnerTaxNumberGetWithHttpInfo(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, null, null);
        Type localVarReturnType = new TypeToken<Wrapper13>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entities from A_BusinessPartnerTaxNumber (asynchronously)
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerTaxNumberGetAsync(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, final ApiCallback<Wrapper13> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Wrapper13>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aBusinessPartnerTaxNumberPost */
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberPostCall(APIBUSINESSPARTNERABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aBusinessPartnerTaxNumberType;
        
        // create path and map variables
        String localVarPath = "/A_BusinessPartnerTaxNumber".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aBusinessPartnerTaxNumberPostValidateBeforeCall(APIBUSINESSPARTNERABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberPostCall(aBusinessPartnerTaxNumberType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add new entity to A_BusinessPartnerTaxNumber
     * 
     * @param aBusinessPartnerTaxNumberType New entity (optional)
     * @return CreatedABusinessPartnerTaxNumberType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberPost(APIBUSINESSPARTNERABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType) throws ApiException {
        ApiResponse<CreatedABusinessPartnerTaxNumberType> resp = aBusinessPartnerTaxNumberPostWithHttpInfo(aBusinessPartnerTaxNumberType);
        return resp.getData();
    }

    /**
     * Add new entity to A_BusinessPartnerTaxNumber
     * 
     * @param aBusinessPartnerTaxNumberType New entity (optional)
     * @return ApiResponse&lt;CreatedABusinessPartnerTaxNumberType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedABusinessPartnerTaxNumberType> aBusinessPartnerTaxNumberPostWithHttpInfo(APIBUSINESSPARTNERABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType) throws ApiException {
        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberPostValidateBeforeCall(aBusinessPartnerTaxNumberType, null, null);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerTaxNumberType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add new entity to A_BusinessPartnerTaxNumber (asynchronously)
     * 
     * @param aBusinessPartnerTaxNumberType New entity (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aBusinessPartnerTaxNumberPostAsync(APIBUSINESSPARTNERABusinessPartnerTaxNumberType aBusinessPartnerTaxNumberType, final ApiCallback<CreatedABusinessPartnerTaxNumberType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aBusinessPartnerTaxNumberPostValidateBeforeCall(aBusinessPartnerTaxNumberType, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedABusinessPartnerTaxNumberType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
