/*
 * OData Service for Business Partner
 * This service enables you to create, read, update, and    delete master data related to Business Partners,    Suppliers, and Customers in an SAP S/4HANA system.
 *
 * OpenAPI spec version: 1 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sap.apibhub.sdk.api_business_partner.api;

import com.sap.apibhub.sdk.client.ApiCallback;
import com.sap.apibhub.sdk.client.ApiClient;
import com.sap.apibhub.sdk.client.ApiException;
import com.sap.apibhub.sdk.client.ApiResponse;
import com.sap.apibhub.sdk.client.Configuration;
import com.sap.apibhub.sdk.client.Pair;
import com.sap.apibhub.sdk.client.ProgressRequestBody;
import com.sap.apibhub.sdk.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.sap.apibhub.sdk.api_business_partner.model.APIBUSINESSPARTNERASupplierPurchasingOrgType;
import com.sap.apibhub.sdk.api_business_partner.model.CreatedASupplierPurchasingOrgType;
import com.sap.apibhub.sdk.api_business_partner.model.ModifiedASupplierPurchasingOrgType;
import com.sap.apibhub.sdk.api_business_partner.model.OdataError;
import com.sap.apibhub.sdk.api_business_partner.model.Wrapper25;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ASupplierPurchasingOrgApi {
    private ApiClient apiClient;

    public ASupplierPurchasingOrgApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ASupplierPurchasingOrgApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for aSupplierPurchasingOrgGet */
    private com.squareup.okhttp.Call aSupplierPurchasingOrgGetCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, List<String> expand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_SupplierPurchasingOrg".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (top != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$top", top));
        if (skip != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$skip", skip));
        if (filter != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$filter", filter));
        if (inlinecount != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "$inlinecount", inlinecount));
        if (orderby != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$orderby", orderby));
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));
        if (expand != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$expand", expand));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aSupplierPurchasingOrgGetValidateBeforeCall(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, List<String> expand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgGetCall(top, skip, filter, inlinecount, orderby, select, expand, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entities from A_SupplierPurchasingOrg
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @return Wrapper25
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Wrapper25 aSupplierPurchasingOrgGet(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, List<String> expand) throws ApiException {
        ApiResponse<Wrapper25> resp = aSupplierPurchasingOrgGetWithHttpInfo(top, skip, filter, inlinecount, orderby, select, expand);
        return resp.getData();
    }

    /**
     * Get entities from A_SupplierPurchasingOrg
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @return ApiResponse&lt;Wrapper25&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Wrapper25> aSupplierPurchasingOrgGetWithHttpInfo(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, List<String> expand) throws ApiException {
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, expand, null, null);
        Type localVarReturnType = new TypeToken<Wrapper25>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entities from A_SupplierPurchasingOrg (asynchronously)
     * 
     * @param top Show only the first n items, see [OData Paging - Top](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374630) (optional)
     * @param skip Skip the first n items, see [OData Paging - Skip](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374631) (optional)
     * @param filter Filter items by property values, see [OData Filtering](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374625) (optional)
     * @param inlinecount Include count of items, see [OData Count](http://www.odata.org/documentation/odata-version-2-0/uri-conventions/#InlinecountSystemQueryOption) (optional)
     * @param orderby Order items by property values, see [OData Sorting](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374629) (optional)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aSupplierPurchasingOrgGetAsync(Integer top, Integer skip, String filter, String inlinecount, List<String> orderby, List<String> select, List<String> expand, final ApiCallback<Wrapper25> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aSupplierPurchasingOrgGetValidateBeforeCall(top, skip, filter, inlinecount, orderby, select, expand, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Wrapper25>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aSupplierPurchasingOrgPost */
    private com.squareup.okhttp.Call aSupplierPurchasingOrgPostCall(APIBUSINESSPARTNERASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aSupplierPurchasingOrgType;
        
        // create path and map variables
        String localVarPath = "/A_SupplierPurchasingOrg".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aSupplierPurchasingOrgPostValidateBeforeCall(APIBUSINESSPARTNERASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgPostCall(aSupplierPurchasingOrgType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Add new entity to A_SupplierPurchasingOrg
     * 
     * @param aSupplierPurchasingOrgType New entity (optional)
     * @return CreatedASupplierPurchasingOrgType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedASupplierPurchasingOrgType aSupplierPurchasingOrgPost(APIBUSINESSPARTNERASupplierPurchasingOrgType aSupplierPurchasingOrgType) throws ApiException {
        ApiResponse<CreatedASupplierPurchasingOrgType> resp = aSupplierPurchasingOrgPostWithHttpInfo(aSupplierPurchasingOrgType);
        return resp.getData();
    }

    /**
     * Add new entity to A_SupplierPurchasingOrg
     * 
     * @param aSupplierPurchasingOrgType New entity (optional)
     * @return ApiResponse&lt;CreatedASupplierPurchasingOrgType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedASupplierPurchasingOrgType> aSupplierPurchasingOrgPostWithHttpInfo(APIBUSINESSPARTNERASupplierPurchasingOrgType aSupplierPurchasingOrgType) throws ApiException {
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgPostValidateBeforeCall(aSupplierPurchasingOrgType, null, null);
        Type localVarReturnType = new TypeToken<CreatedASupplierPurchasingOrgType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add new entity to A_SupplierPurchasingOrg (asynchronously)
     * 
     * @param aSupplierPurchasingOrgType New entity (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aSupplierPurchasingOrgPostAsync(APIBUSINESSPARTNERASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ApiCallback<CreatedASupplierPurchasingOrgType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aSupplierPurchasingOrgPostValidateBeforeCall(aSupplierPurchasingOrgType, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedASupplierPurchasingOrgType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGet */
    private com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetCall(String supplier, String purchasingOrganization, List<String> select, List<String> expand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/A_SupplierPurchasingOrg(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "Supplier" + "\\}", apiClient.escapeString(supplier.toString()))
        .replaceAll("\\{" + "PurchasingOrganization" + "\\}", apiClient.escapeString(purchasingOrganization.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (select != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$select", select));
        if (expand != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "$expand", expand));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetValidateBeforeCall(String supplier, String purchasingOrganization, List<String> select, List<String> expand, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'supplier' is set
        if (supplier == null) {
            throw new ApiException("Missing the required parameter 'supplier' when calling aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGet(Async)");
        }
        
        // verify the required parameter 'purchasingOrganization' is set
        if (purchasingOrganization == null) {
            throw new ApiException("Missing the required parameter 'purchasingOrganization' when calling aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGet(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetCall(supplier, purchasingOrganization, select, expand, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get entity from A_SupplierPurchasingOrg by key
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @return CreatedASupplierPurchasingOrgType
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CreatedASupplierPurchasingOrgType aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGet(String supplier, String purchasingOrganization, List<String> select, List<String> expand) throws ApiException {
        ApiResponse<CreatedASupplierPurchasingOrgType> resp = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetWithHttpInfo(supplier, purchasingOrganization, select, expand);
        return resp.getData();
    }

    /**
     * Get entity from A_SupplierPurchasingOrg by key
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @return ApiResponse&lt;CreatedASupplierPurchasingOrgType&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CreatedASupplierPurchasingOrgType> aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetWithHttpInfo(String supplier, String purchasingOrganization, List<String> select, List<String> expand) throws ApiException {
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetValidateBeforeCall(supplier, purchasingOrganization, select, expand, null, null);
        Type localVarReturnType = new TypeToken<CreatedASupplierPurchasingOrgType>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get entity from A_SupplierPurchasingOrg by key (asynchronously)
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param select Select properties to be returned, see [OData Select](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374620) (optional)
     * @param expand Expand related entities, see [OData Expand](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html#_Toc445374621) (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetAsync(String supplier, String purchasingOrganization, List<String> select, List<String> expand, final ApiCallback<CreatedASupplierPurchasingOrgType> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationGetValidateBeforeCall(supplier, purchasingOrganization, select, expand, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CreatedASupplierPurchasingOrgType>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /* Build call for aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatch */
    private com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchCall(String supplier, String purchasingOrganization, ModifiedASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = aSupplierPurchasingOrgType;
        
        // create path and map variables
        String localVarPath = "/A_SupplierPurchasingOrg(Supplier='{Supplier}',PurchasingOrganization='{PurchasingOrganization}')".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "Supplier" + "\\}", apiClient.escapeString(supplier.toString()))
        .replaceAll("\\{" + "PurchasingOrganization" + "\\}", apiClient.escapeString(purchasingOrganization.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {"APIBHUB_SANDBOX_APIKEY", "basicAuthentication" };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchValidateBeforeCall(String supplier, String purchasingOrganization, ModifiedASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'supplier' is set
        if (supplier == null) {
            throw new ApiException("Missing the required parameter 'supplier' when calling aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatch(Async)");
        }
        
        // verify the required parameter 'purchasingOrganization' is set
        if (purchasingOrganization == null) {
            throw new ApiException("Missing the required parameter 'purchasingOrganization' when calling aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatch(Async)");
        }
        
        
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchCall(supplier, purchasingOrganization, aSupplierPurchasingOrgType, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Update entity in A_SupplierPurchasingOrg
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param aSupplierPurchasingOrgType New property values (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatch(String supplier, String purchasingOrganization, ModifiedASupplierPurchasingOrgType aSupplierPurchasingOrgType) throws ApiException {
        aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchWithHttpInfo(supplier, purchasingOrganization, aSupplierPurchasingOrgType);
    }

    /**
     * Update entity in A_SupplierPurchasingOrg
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param aSupplierPurchasingOrgType New property values (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchWithHttpInfo(String supplier, String purchasingOrganization, ModifiedASupplierPurchasingOrgType aSupplierPurchasingOrgType) throws ApiException {
        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchValidateBeforeCall(supplier, purchasingOrganization, aSupplierPurchasingOrgType, null, null);
        return apiClient.execute(call);
    }

    /**
     * Update entity in A_SupplierPurchasingOrg (asynchronously)
     * 
     * @param supplier Vendor Account Number   Alphanumeric key uniquely identifying the document.   With the supplier number, information from the supplier master record (such as the supplier&#39;s address and bank details) is copied into a purchasing document (such as a request for quotation or a purchase order).You can use the supplier number to keep track of requests for quotation, purchase orders and outline agreements. (required)
     * @param purchasingOrganization Purchasing Organization   Denotes the purchasing organization. (required)
     * @param aSupplierPurchasingOrgType New property values (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchAsync(String supplier, String purchasingOrganization, ModifiedASupplierPurchasingOrgType aSupplierPurchasingOrgType, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = aSupplierPurchasingOrgSupplierSupplierPurchasingOrganizationPurchasingOrganizationPatchValidateBeforeCall(supplier, purchasingOrganization, aSupplierPurchasingOrgType, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
